### ISSUE TITLE
There is no decoder.c & encoder.c in encode folder

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-lite#42] opened 2019-03-21 03:22 UTC
When I build the example in IDE,it remind me that there is no encoder.c&decoder.c,I checked the folder and I didn`t find them,either.

**Comment by zjkmxy** [comment] 2019-03-21 03:27
Yes, because all functions are static inline. Those .c files don't exist from beginning.
Maybe your project configuration has some problem?
What's your platform? NRF?

**Comment by Heath68** [comment] 2019-03-21 06:30
SES,I ran the ndn-iot-package-over-nordic-sdk BLE example,but SES reminded me those errors.

**Comment by Zhiyi-Zhang** [comment] 2019-03-27 05:08
@peurpdapeurp @RoySCU Any ideas on this issue?

**Comment by peurpdapeurp** [comment] 2019-03-27 05:13
Yes; this is an issue that was brought up in the ndn-lite-over-nordic-sdk repository as well, and is currently being addressed; it is likely that this is because the ndn-lite-over-nordic-sdk repository was not updated for some time and was no longer compatible with the newest version of ndn-lite. I am in the process of updating it now. The duplicate of this issue in the other repository is here: https://github.com/named-data-iot/ndn-iot-package-over-nordic-sdk/issues/3

**Closed** 2019-08-16 03:34 UTC
